// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Placeholder Firebase configuration.
///
/// **TODO**: Replace with the real output of `flutterfire configure`.
/// This file is auto-generated by FlutterFire CLI and should not be
/// edited manually once properly configured.
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web platform is not supported');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZzZgJ9gEG3r2bgp8tpjE9JiWA0r6Urzg',
    appId: '1:1071092637851:android:eacb5641382ca6cfb5663e',
    messagingSenderId: '1071092637851',
    projectId: 'finflow-c38e8',
    storageBucket: 'finflow-c38e8.firebasestorage.app',
  );

  /// Android-specific Firebase options.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0C_eZsGJyY8CN9oVJN9ELr-3EYmzF-3k',
    appId: '1:1071092637851:ios:d3bb90b56a238513b5663e',
    messagingSenderId: '1071092637851',
    projectId: 'finflow-c38e8',
    storageBucket: 'finflow-c38e8.firebasestorage.app',
    iosBundleId: 'com.finflow.finflow',
  );

  /// iOS-specific Firebase options.
}